name: prj

services:
  svc:
    build: .
    env_file: "service.env"
    environment:
      SHELL:  # Inherits shell environment variable value
      TERM:   # Inherits shell environment variable value
      USER:   # Inherits shell environment variable value
      HOME:   # Inherits shell environment variable value
      UNKNOWN: ${UNKNOWN}
      CUSTOM_VAR_1: ${CUSTOM_VAR_1}
      CUSTOM_VAR_2: ${CUSTOM_VAR_2}
      CUSTOM_VAR_3: ${CUSTOM_VAR_3}
# NOTE: SERVICE_A does not need to be specified
# NOTE: SERVICE_B does not need to be specified
# NOTE: SERVICE_C does not need to be specified
      DOCKERFILE_VAR_I: Overridden ALPHA
      DOCKERFILE_VAR_II: Overridden BRAVO
      DOCKERFILE_VAR_III: Overridden CHARLIE