reg delete HKLM\SOFTWARE\Classes\LibraryFolder\background\shell\skull /f
reg delete HKLM\SOFTWARE\Classes\LibraryFolder\shell\skull /f
reg delete HKLM\SOFTWARE\Classes\Drive\shell\skull /f
reg delete HKLM\SOFTWARE\Classes\Directory\Background\shell\skull /f
reg delete HKLM\SOFTWARE\Classes\Directory\shell\skull /f
reg delete HKLM\SOFTWARE\Classes\*\shell\skull /f
reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\skull_delete /f
reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\skull_update /f
reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\skull_retrieve /f
reg delete HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CommandStore\shell\skull_create /f
